import { NextIntlClientProvider, hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { Metadata } from "next";
import "../globals.css";
import { Nunito } from "next/font/google";
import { ThemesProvider } from "../ThemeProvider";

const fontNunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  // Ensure that the incoming `locale` is valid
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html suppressHydrationWarning lang={locale}>
      <body className={`${fontNunito.variable} antialiased font-nunito`}>
        <NextIntlClientProvider>
          <ThemesProvider>{children}</ThemesProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
